# Importing Libraries

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report,confusion_matrix
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC


# Loading Data

In [3]:
data = pd.read_csv('spam.csv', encoding='ISO-8859-1')
data.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [4]:
data['v1'].value_counts()

v1
ham     4825
spam     747
Name: count, dtype: int64

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   v1          5572 non-null   object
 1   v2          5572 non-null   object
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: object(5)
memory usage: 217.8+ KB


In [6]:
data.duplicated().sum()

403

In [7]:
data.drop_duplicates()

v1                                                 v2 Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...    ...                                                ...        ...   
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will Ì_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN  
1           NaN        NaN  
2           NaN        NaN  
3           NaN        NaN  
4           NaN        NaN  
...         ...        ...  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN  

[5169 rows x 5 columns]

In [8]:
data.isnull().sum()

v1               0
v2               0
Unnamed: 2    5522
Unnamed: 3    5560
Unnamed: 4    5566
dtype: int64

In [9]:
data.dropna()

v1                                                 v2  \
281   ham                                \Wen u miss someone   
1038  ham  Edison has rightly said, \A fool can ask more ...   
2255  ham      I just lov this line: \Hurt me with the truth   
3525  ham  \HEY BABE! FAR 2 SPUN-OUT 2 SPK AT DA MO... DE...   
4668  ham  When I was born, GOD said, \Oh No! Another IDI...   
5048  ham  Edison has rightly said, \A fool can ask more ...   

                                             Unnamed: 2  \
281    the person is definitely special for u..... B...   
1038                                                 GN   
2255                                       I don't mind   
3525                                   HAD A COOL NYTHO   
4668                                           GOD said   
5048                                                 GN   

                                    Unnamed: 3  \
281                           why to miss them   
1038                                        GE   
2255  i wil tolerat.bcs ur my someone..... But   
3525                            TX 4 FONIN HON   
4668          \"OH No! COMPETITION\". Who knew   
5048                                        GE   

                                             Unnamed: 4  
281                       just Keep-in-touch\" gdeve.."  
1038                                            GNT:-)"  
2255   Never comfort me with a lie\" gud ni8 and swe...  
3525                CALL 2MWEN IM BK FRMCLOUD 9! J X\""  
4668    one day these two will become FREINDS FOREVER!"  
5048                                            GNT:-)"

In [10]:
df = data[['v1', 'v2']]

In [11]:
df.head()

v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [12]:
df = df[['v1', 'v2']]
df.columns = ['label', 'message']


In [13]:
df = df.dropna(subset=['label', 'message'])


In [14]:
# Drop rows with any null values in 'label' or 'message'
df.dropna(subset=['label', 'message'], inplace=True)

# Map 'label' to binary values and remove any rows that didn't map correctly
df['label'] = df['label'].map({'ham': 0, 'spam': 1})

# Drop rows with NaNs in 'label' after mapping
df.dropna(subset=['label'], inplace=True)

# Ensure 'label' is of integer type
df['label'] = df['label'].astype(int)

In [15]:
df.head()

label                                            message
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...

# Training Model

In [16]:
X_train, X_test, y_train, y_test = train_test_split(df['message'], df['label'], test_size=0.2, random_state=42)


In [17]:
print("y_train type:", y_train.dtype)
print("y_test type:", y_test.dtype)

y_train type: int64
y_test type: int64


In [18]:
print("X_train type:", X_train.dtype)
print("x_test type:", X_test.dtype)

X_train type: object
x_test type: object


In [30]:
y_test.value_counts()

label
0    965
1    150
Name: count, dtype: int64

Applying TF-IDF Vectorization to differentiate spam messages.

In [19]:
vectorizer = TfidfVectorizer(stop_words='english')
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)


Function to print result

In [23]:
def train_and_evaluate_model(model, model_name):
    model.fit(X_train_tfidf, y_train)
    y_pred = model.predict(X_test_tfidf)
    print(f"{model_name} Evaluation:")
    print("Accuracy:", accuracy_score(y_test, y_pred))
    print("Classification Report:")
    print(classification_report(y_test, y_pred))
    print("Confusion Matrix:")
    print(confusion_matrix(y_test, y_pred))
    print("-" * 60)

Logistic ReRegression Model

In [28]:
clf = LogisticRegression()
train_and_evaluate_model(clf, "Logistic Regression")

Logistic Regression Evaluation:
Accuracy: 0.9524663677130045
Classification Report:
              precision    recall  f1-score   support

           0       0.95      1.00      0.97       965
           1       0.97      0.67      0.79       150

    accuracy                           0.95      1115
   macro avg       0.96      0.83      0.88      1115
weighted avg       0.95      0.95      0.95      1115

Confusion Matrix:
[[962   3]
 [ 50 100]]
------------------------------------------------------------


Multinomial Naive Bayes Model

In [27]:
clf_nb = MultinomialNB()
train_and_evaluate_model(clf_nb, "Naive Bayes")


Naive Bayes Evaluation:
Accuracy: 0.9668161434977578
Classification Report:
              precision    recall  f1-score   support

           0       0.96      1.00      0.98       965
           1       1.00      0.75      0.86       150

    accuracy                           0.97      1115
   macro avg       0.98      0.88      0.92      1115
weighted avg       0.97      0.97      0.96      1115

Confusion Matrix:
[[965   0]
 [ 37 113]]
------------------------------------------------------------


SVM Model

In [24]:
# Support Vector Machine
clf_svm = SVC(kernel='linear', probability=True)
train_and_evaluate_model(clf_svm, "Support Vector Machine")

Support Vector Machine Evaluation:
Accuracy: 0.979372197309417
Classification Report:
              precision    recall  f1-score   support

           0       0.98      1.00      0.99       965
           1       0.97      0.87      0.92       150

    accuracy                           0.98      1115
   macro avg       0.98      0.93      0.95      1115
weighted avg       0.98      0.98      0.98      1115

Confusion Matrix:
[[961   4]
 [ 19 131]]
------------------------------------------------------------


After comparing all models SVM is more accurate to identify spam sms.